### PR TITLE
Adding Required files and folders to the Repo

### PR DESCRIPTION
**Pull request by JoE11-y**
Kindly note all files are empty and are yet to be populated with codes.
This just serves as the creation of the layout of the repo

### CODE REVIEW

**Comment by JoE11-y** [comment]
This pull request does justice to issue #2

**Comment by epikoder** [comment]
File names still contain uniswap?

**Comment by JoE11-y** [comment]
> File names still contain uniswap?

Yes. I tried to just cloned it as it was on pancakeswap.
Features and names have not yet been decided by the team.
It's just to give us a structure.
All files are empty.
Names can be edited as codes are being written in them.

**Comment by epikoder** [comment]
Okay.. buh the naming convention shouldn't be difficult to conclude. Naming should be by overall function.
`Migration.sol` then the changes will reflect on the import section of the code

**Comment by JoE11-y** [comment]
Alright sir.
I'll close this PR and wait till we've concluded on how we are going about the naming convention.

**Pull request closed without merging**
